on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.3.9
    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_WORKSPACE: default
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform Init
        working-directory: ./deployment
        run: terraform init
      - name: Terraform Apply
        working-directory: ./deployment
        run: terraform apply -auto-approve
